import { images } from "../constants"

/* Blog data JSON */
const blogPostData = [
    {
        id: 1,
        img: images.blog1,
        label: "nature",
        title: "Into the Outback",
        description: "An epic and ancient landscape, deeply entwined with the artistic, musical, and spiritual traditions of Indigenous Australians, the Outback is one of the largest remaining, intact natural areas on Earth.",
        content: "Known for its Aboriginal peoples and its vast, ancient landscapes, the Outback is an incredibly special place for me. I think that once you get that distinctive red dust in your blood it never comes out. My roots are deeply connected to the rural areas of western Queensland and from a very young age, the never-ending expanse of inland Australia has been something that has captivated me. Ever since I can remember, we would take long road trips out to a family-run cattle station, and there was always this great sense of wonder and adventure.\n\n In the Outback, you can travel for days in any direction and stumble across places that are unique, untouched, and rarely visited. It was on these early trips that I fell in love with the bush, the people, and its landscape. I’ve never stopped venturing back. Drawn to remote, wide open spaces, to the dusty and the desolate, I have found that there are countless unique rocky outcrops and ridges to explore. From the arid and ancient regions of Kimberly and Pilbara in Western Australia, to the rugged, weathered peaks and dramatic rocky gorges found in the Flinders Ranges of South Australia, to the red centre and Australia’s most famous monolith, Uluru — it is not only the sheer size of the Outback that is astounding (it could encompass almost all of Europe), it is also home to some of the world’s most spectacular and untouched landscapes.\n\n Over the past few years, I’ve been lucky enough to photograph, film, and fly over these regions — both in light aircraft, and more recently, with drones. Deeply entwined with the landscape itself are the artistic, musical, and spiritual traditions of the Indigenous Australians, among the longest surviving cultural traditions in human history. Some 30,000 to 70,000 years ago — many millennia before the European colonisation that would come to threaten and profoundly disrupt many Aboriginal communities — the first inhabitants of Australia arrived from the north, making them amongst the world’s earlier mariners. They spread throughout the landmass, surviving even the harsh climatic conditions of the Last Glacial Maximum. Evidence of ancient Aboriginal art is found all over the Outback, most notably at Uluru and Kakadu National Park in the Northern Territory. An impressive sandstone rock formation, Uluṟu — as it called by the Pitjantjatjara Anangu, the Aboriginal people of the area — or Ayers Rock, still holds great sacred and cultural significance for the local indigenous population. Appearing to change color at different times of year, this natural monolith is quite magnificent as it glows a deep red or purple at sunrise and sunset."
    },
    {
        id: 2,
        img: images.blog2,
        label: "ocean",
        title: "In Danger: The Great Barrier Reef",
        description: "With an unprecedented amount of dredging damaging its fragile ecosystem, UNESCO is threatening to downgrade the GBR to the World Heritage ‘In Danger’ list. ",
        content: "For decades, the Great Barrier Reef has enjoyed World Heritage Status and been synonymous with diving, tourism and with Australia. But in June of 2014, UNESCO threatened to downgrade the Great Barrier Reef to the World Heritage ‘In Danger’ list; a category populated predominantly by war-torn and developing nations.\n\n The final decision will be made next month, in February 2015. UNESCO’s concerns are focused on the issue of industrial development along the reef. Queensland has one of the largest deposits of coal, and with developed markets slowly turning their back on dirty energy, there’s huge momentum to dig it up and ship it out as fast as possible before falling prices make it no longer viable.\n\n To do this requires unprecedented amounts of dredging, both to expand existing coal ports and to create new ones, many of which are located within the boundaries of the Barrier Reef Marine Park. Dredging is problematic for a few reasons. Firstly it digs up seagrass meadows, removing valuable grazing areas for dugongs and turtles, secondly it creates a toxic soup of heavy metals which can severely impact on the health of marine life. And lastly, the dredge spoils are then dumped back out onto the Barrier Reef and can travel for miles up the coast clogging coral polyps and smothering entire reef systems.\n Gladstone harbour has been the focus of the debate around port expansion in Queensland. The port of Gladstone has permission to dredge 32 million tonnes of sea bed in order to expedite the shipment of coal and LNG from Curtis Island. Reports from fishermen of diseased fish, as well as an environmental disaster which coincided with a leaking bund wall in 2011, resulted in dead turtles and dugongs washing up on the beach and millions of tonnes of dredge spoil spilling out into the harbour and inner reefs. The local fishing industry has collapsed as a result."
    },
    {
        id: 3,
        img: images.blog3,
        label: "culture",
        title: "Uluru Rises",
        description: "On a road trip through Australia’s Northern Territory I am privileged to receive a rich and emotional glimpse into Aboriginal culture. A profoundly spiritual people, Aborigines have a deep connection with the land, nurture respect for their elders, and believe that true knowledge comes from their ancestors.",
        content: "To truly know and understand Australia we must arguably appreciate Aborigine culture. These people have survived natural disasters, near extinction, and a period of mistreatment at the hands of white settlers. And although their numbers have dwindled, their talents as master storytellers have ensured that many can still recount the stories of their ancestors, often for generations and generations back.\n\n From what I have read Aborigine culture and American Indian culture have a lot in common — a deep connection with the land, animals and plants, they are profoundly spiritual people, they nurture respect for their elders and believe that true knowledge can only be passed down and received from their ancestors, and they have both endured violent struggles with white settlers. Although over time the aboriginal “tribes” have settled throughout Australia, forced apart by nature or settlers, the Aborigines are all inextricably connected to one another.\n\n Uluru rises up from the landscape as one approaches it from the Lasseter Highway. Its red hue dramatically contrasts against a clear blue sky almost forcing you to stop and take in the sight for a few minutes. Although we have all seen it pictured hundreds of times, nothing can quite prepare you for the omnipresence of the approximately 600 million-year-old limestone rock, which has been the spiritual home to Australia’s Aborigines for some 80 million years. In the evening onlookers are treated to one of the most spectacular light shows on Earth as Uluru reflects the glow of the setting sun. Steadily and silently it changes color from reddish-brown through red to magenta to purple and finally to brown as the sun finally dips below the horizon. Hundreds gather at the edges of the sacred land surrounding the rock to witness the same spectacle as the Anagus, Uluru’s traditional landowners, have observed for millennia. Personally I could not help but feel the aura and power of this great mass, which has been the spiritual home to so many through the centuries."
    },    
    {
        id: 4,
        img: images.blog4,
        label: "nature",
        title: "Abstract Australia from Above",
        description: "The Australian landscape has always appealed to me. There is something about it— its spaciousness, its character, the light and its uniqueness.",
        content: "I have been attracted to the Australian landscape because of its size and subtle differences — a sense of wonderment, how it all came about, the evolution of the landscape. Like the rest of the world it has gone through many stages to be what it is today — uniquely Australian. But it also is a very old landscape.\n\n It is the flattest and driest continent, which compared with other countries, does not manifest itself in grandeur as we know it; large rivers, large mountains and the dramatic changes of the seasons. However, I found that by looking at the landscape from the air, many natural characteristics revealed themselves much better, showing the evolution and the geographical variations. Nature is a great teacher. Observing and experiencing it can stimulate our creative senses which in turn is beneficial to ourselves and our environment. It was in 1955 that I bought my first camera, and this was the beginning of a long association with photography. Intrigued by the unusualness of the Australian landscape, I became a landscape photographer with a strong bias for aerial photography, which I felt captured the vastness of the outback best — each flight became a flight of discovery.\n\n There are so many Australian landscapes worthy of consideration whether they be rivers, coastal plains or deserts — all of which vary seasonally and at different times of the day. As much as possible I like to be inspired by what I see and this is where I experience a sense of wonderment of a world so complex, varied and beautiful. Of course there are many ways to appreciate the landscape. My own involvement is to photograph the highlights and to interpret them with the camera in a painterly way. I emphasise these highlights by pointing the camera down and focussing on the subject, excluding the horizon so one looses a point of reference and the reality often takes on an abstract view. I hope that the character of the subject is enhanced and that it reveals more through isolation by the camera angle."
    },
]

export default blogPostData;